//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Titles", typeof(Titles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект #{0}{1} загружен без ошибок..
        /// </summary>
        public static string AboutCorrectItem {
            get {
                return ResourceManager.GetString("AboutCorrectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---Вы редактируете объект---.
        /// </summary>
        public static string AboutEdit {
            get {
                return ResourceManager.GetString("AboutEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При создании объекта #{0}{1} произошли следующие ошибки:.
        /// </summary>
        public static string AboutErrorToImport {
            get {
                return ResourceManager.GetString("AboutErrorToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группировка по &apos;{0}&apos;:.
        /// </summary>
        public static string AboutGrouping {
            get {
                return ResourceManager.GetString("AboutGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запись содержит некорректный тип:.
        /// </summary>
        public static string AboutIncorrectTypeItem {
            get {
                return ResourceManager.GetString("AboutIncorrectTypeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{0}{1}
        ///.
        /// </summary>
        public static string AboutItem {
            get {
                return ResourceManager.GetString("AboutItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите название книги:,Укажите авторов книги:,Укажите город издания книги:,Укажите название издательства книги:,Укажите год издания книги:,Укажите количество страниц книги:,Укажите примечание к книге:,Укажите ISBN книги:.
        /// </summary>
        public static string AskAboutBook {
            get {
                return ResourceManager.GetString("AskAboutBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите название газеты:,Укажите город издания газеты:,Укажите название издательства газеты:,Укажите год издания газеты:,Укажите количество страниц газеты:,Укажите примечание к газете:,Укажите номер газеты:,Укажите дату газеты:,Укажите ISSN газеты:.
        /// </summary>
        public static string AskAboutNewspaper {
            get {
                return ResourceManager.GetString("AskAboutNewspaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите название патента:,Укажите изобретателей патента:,Укажите страну патента:,Укажите регистрационный номер патента:,Укажите дату подачи заяки патента:,Укажите дату публикации патента:,Укажите количество страниц патента:,Укажите примечание к патенту:.
        /// </summary>
        public static string AskAboutPatent {
            get {
                return ResourceManager.GetString("AskAboutPatent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите номер записи для удаления из Каталога:.
        /// </summary>
        public static string AskToDelete {
            get {
                return ResourceManager.GetString("AskToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите номер записи для редактирования:.
        /// </summary>
        public static string AskToEdit {
            get {
                return ResourceManager.GetString("AskToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторы:.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не указали Автора книги. Вместо него указано значение по умолчанию: {0}..
        /// </summary>
        public static string AuthorsError {
            get {
                return ResourceManager.GetString("AuthorsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог пуст или не содержит книг.
        ///Нажмите любую кнопку для выходя в Главное меню....
        /// </summary>
        public static string CatalogIsEmptyOrHasNotBook {
            get {
                return ResourceManager.GetString("CatalogIsEmptyOrHasNotBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SavedFiles.
        /// </summary>
        public static string CatalogToFile {
            get {
                return ResourceManager.GetString("CatalogToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место издательства (Город):.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не указали Место издания (город). Вместо него указано значение по умолчанию: {0}..
        /// </summary>
        public static string CityError {
            get {
                return ResourceManager.GetString("CityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все записи из файла {0}\{1} загружены в Каталог..
        /// </summary>
        public static string CorrectImport {
            get {
                return ResourceManager.GetString("CorrectImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записи из файла {0}\{1} загружены в Каталог.
        ///Лог проверки загрузки смотрите в файле {0}\{2}..
        /// </summary>
        public static string CorrectImportWithLog {
            get {
                return ResourceManager.GetString("CorrectImportWithLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна:.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не указали Страну патента. Вместо нее указано значение по умолчанию: {0}..
        /// </summary>
        public static string CountryError {
            get {
                return ResourceManager.GetString("CountryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата:.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы указали Дату газеты не в формате дд.мм.гггг. Вместо нее указано значение по умолчанию: {0}..
        /// </summary>
        public static string DateNewsError {
            get {
                return ResourceManager.GetString("DateNewsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы указали Дату публикации не в формате дд.мм.гггг или год ранее 1950. Вместо нее указано значение по умолчанию: {0}..
        /// </summary>
        public static string DatePPatentError {
            get {
                return ResourceManager.GetString("DatePPatentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата публикации:.
        /// </summary>
        public static string DatePublication {
            get {
                return ResourceManager.GetString("DatePublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата подачи заявки:.
        /// </summary>
        public static string DateRequest {
            get {
                return ResourceManager.GetString("DateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы указали Дату подачи заявки не в формате дд.мм.гггг или год ранее 1950. Вместо нее указано значение по умолчанию: {0}..
        /// </summary>
        public static string DateRPatentError {
            get {
                return ResourceManager.GetString("DateRPatentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор по умолчанию.
        /// </summary>
        public static string DefaultAuthor {
            get {
                return ResourceManager.GetString("DefaultAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город по умолчанию.
        /// </summary>
        public static string DefaultCity {
            get {
                return ResourceManager.GetString("DefaultCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страна по умолчанию.
        /// </summary>
        public static string DefaultCountry {
            get {
                return ResourceManager.GetString("DefaultCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изобретатель по умолчанию.
        /// </summary>
        public static string DefaultInventor {
            get {
                return ResourceManager.GetString("DefaultInventor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Издательство по умолчанию.
        /// </summary>
        public static string DefaultPublisher {
            get {
                return ResourceManager.GetString("DefaultPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-{1}/{2}.
        /// </summary>
        public static string DefaultRegNumber {
            get {
                return ResourceManager.GetString("DefaultRegNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название по умолчанию.
        /// </summary>
        public static string DefaultTitle {
            get {
                return ResourceManager.GetString("DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы удалили запись #{0}..
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Каталог пуст.
        ///Нажмите любую кнопку для выходя в Главное меню....
        /// </summary>
        public static string EmptyCatalog {
            get {
                return ResourceManager.GetString("EmptyCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл {0}\{1} пуст или не содержит записей Каталога..
        /// </summary>
        public static string EmptyFile {
            get {
                return ResourceManager.GetString("EmptyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Во время чтения файла {0}\{1} произошла ошибка:.
        /// </summary>
        public static string ErrorParseXML {
            get {
                return ResourceManager.GetString("ErrorParseXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogImport.txt.
        /// </summary>
        public static string FileOfLog {
            get {
                return ResourceManager.GetString("FileOfLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\SavedFiles\LogImport.txt.
        /// </summary>
        public static string FileToLogWithPath {
            get {
                return ResourceManager.GetString("FileToLogWithPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\SavedFiles\SavedFile.txt.
        /// </summary>
        public static string FileToSaveWithPath {
            get {
                return ResourceManager.GetString("FileToSaveWithPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SavedFile.txt.
        /// </summary>
        public static string FileTXT {
            get {
                return ResourceManager.GetString("FileTXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SavedFile.xml.
        /// </summary>
        public static string FileXML {
            get {
                return ResourceManager.GetString("FileXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}.
        /// </summary>
        public static string FullPath {
            get {
                return ResourceManager.GetString("FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных для группировки..
        /// </summary>
        public static string GroupingIsUnavailable {
            get {
                return ResourceManager.GetString("GroupingIsUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите поисковый запрос:.
        /// </summary>
        public static string InputSeachRequest {
            get {
                return ResourceManager.GetString("InputSeachRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не указали Изобретателя патента. Вместо него указано значение по умолчанию: {0}..
        /// </summary>
        public static string InventorError {
            get {
                return ResourceManager.GetString("InventorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изобретатели:.
        /// </summary>
        public static string Inventors {
            get {
                return ResourceManager.GetString("Inventors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Международный стандартный номер книги (ISBN):.
        /// </summary>
        public static string ISBN {
            get {
                return ResourceManager.GetString("ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы  указали некорректный ISBN. Вместо него указано значение по умолчанию: {0}..
        /// </summary>
        public static string ISBNError {
            get {
                return ResourceManager.GetString("ISBNError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Международный стандартный номер серийного издания (ISSN):.
        /// </summary>
        public static string ISSN {
            get {
                return ResourceManager.GetString("ISSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы  указали некорректный ISSN. Вместо него указано значение по умолчанию: {0}..
        /// </summary>
        public static string ISSNError {
            get {
                return ResourceManager.GetString("ISSNError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В файле {0}\{1} не все записи корректны..
        /// </summary>
        public static string ItemIsIncorrectInFile {
            get {
                return ResourceManager.GetString("ItemIsIncorrectInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---Вы допустили ошибки при создании объекта Каталога---.
        /// </summary>
        public static string ListError {
            get {
                return ResourceManager.GetString("ListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главное меню:
        ///[1]-- Добавить запись в Каталог
        ///[2]-- Редактировать запись
        ///[3]-- Удалить запись из Каталога
        ///[4]-- Просмотр Каталога
        ///[5]-- Поиск по названию
        ///[6]-- Сортировать по году выпуска
        ///[7]-- Поиск книг по автору
        ///[8]-- Поиск и группировка книг по издательству
        ///[9]-- Группировать материалы по году выпуска
        ///[0]-- Экспорт \ Импорт Каталога
        ///
        ///[Q]-- Закончить работу с Каталогом.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить в Каталог:
        ///[1]-- Книга
        ///[2]-- Газета
        ///[3]-- Патент
        ///
        ///[Q]-- Перейти в Главное меню.
        /// </summary>
        public static string MenuToAdd {
            get {
                return ResourceManager.GetString("MenuToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работа с файлами:
        ///[1]-- Экспорт
        ///[2]-- Импорт
        ///
        ///[Q]-- Перейти в Главное меню.
        /// </summary>
        public static string MenuToFiles {
            get {
                return ResourceManager.GetString("MenuToFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка файлов:
        ///[1]-- Недопустимы ошибки
        ///[2]-- Загрузить с ошибками
        ///
        ///[Q]-- Перейти в Главное меню.
        /// </summary>
        public static string MenuToImport {
            get {
                return ResourceManager.GetString("MenuToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировать по году выпуска:
        ///[1]-- По возрастанию
        ///[2]-- По убыванию
        ///
        ///[Q]-- Перейти в Главное меню.
        /// </summary>
        public static string MenuToSortYear {
            get {
                return ResourceManager.GetString("MenuToSortYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы выгрузили Каталог в файл:
        ///{0}\{1}
        ///
        ///Нажмите любую кнопку для выходя в Главное меню....
        /// </summary>
        public static string MessageOfSaveFile {
            get {
                return ResourceManager.GetString("MessageOfSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не существует запись #{0}..
        /// </summary>
        public static string NoExist {
            get {
                return ResourceManager.GetString("NoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не существует файла:
        ///{0}\{1}
        ///
        ///Нажмите любую кнопку для выходя в Главное меню....
        /// </summary>
        public static string NoExistFile {
            get {
                return ResourceManager.GetString("NoExistFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В файле {0}\{1} не все записи соответствуют типу объекта Каталога..
        /// </summary>
        public static string NoParseItem {
            get {
                return ResourceManager.GetString("NoParseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Примечание:.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер:.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы указали Номер газеты меньше, чем 0. Вместо него указано значение по умолчанию: {0}..
        /// </summary>
        public static string NumberNewsError {
            get {
                return ResourceManager.GetString("NumberNewsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество страниц:.
        /// </summary>
        public static string PageCount {
            get {
                return ResourceManager.GetString("PageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы указали Количество страниц меньше, чем 0. Вместо него указано значение по умолчанию: {0}..
        /// </summary>
        public static string PageCountError {
            get {
                return ResourceManager.GetString("PageCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы указали некорректный регистрационный номер патента. Вместо него указано значение по умолчанию: {0}..
        /// </summary>
        public static string PatentRegNumberError {
            get {
                return ResourceManager.GetString("PatentRegNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\SavedFiles\SavedFile.xml.
        /// </summary>
        public static string PathWithXMLtoSave {
            get {
                return ResourceManager.GetString("PathWithXMLtoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите любую кнопку для выходя в Главное меню....
        /// </summary>
        public static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Издательство:.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не указали Издательство. Вместо него указано значение по умолчанию: {0}..
        /// </summary>
        public static string PublisherError {
            get {
                return ResourceManager.GetString("PublisherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрационный номер:.
        /// </summary>
        public static string RegNumber {
            get {
                return ResourceManager.GetString("RegNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---Данные объекта Каталога---.
        /// </summary>
        public static string ResultAddorEdit {
            get {
                return ResourceManager.GetString("ResultAddorEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат поиска с группировкой книги по издательству &apos;{0}&apos;..
        /// </summary>
        public static string ResultGroupByPublisher {
            get {
                return ResourceManager.GetString("ResultGroupByPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---Каталог сгруппированный по годам выпуска материалов---.
        /// </summary>
        public static string ResultGroupByYear {
            get {
                return ResourceManager.GetString("ResultGroupByYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы импортировали файл {0}\{1}..
        /// </summary>
        public static string ResultLoadXML {
            get {
                return ResourceManager.GetString("ResultLoadXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат поиска книги по автору &apos;{0}&apos;..
        /// </summary>
        public static string ResultSearchOfAuthors {
            get {
                return ResourceManager.GetString("ResultSearchOfAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результат поиска по названию &apos;{0}&apos;..
        /// </summary>
        public static string ResultSearchOfTitle {
            get {
                return ResourceManager.GetString("ResultSearchOfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить в:
        ///[1]-- Специальный формат
        ///[2]-- XML
        ///
        ///[Q]-- Перейти в Главное меню.
        /// </summary>
        public static string SavedTypeMunu {
            get {
                return ResourceManager.GetString("SavedTypeMunu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Тип записи:{0}#.
        /// </summary>
        public static string SaveType {
            get {
                return ResourceManager.GetString("SaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---КАТАЛОГ---.
        /// </summary>
        public static string ShowCatalog {
            get {
                return ResourceManager.GetString("ShowCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---------------------------------.
        /// </summary>
        public static string Split {
            get {
                return ResourceManager.GetString("Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название:.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не указали Название. Вместо него указано значение по умолчанию: {0}..
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Книга#.
        /// </summary>
        public static string TypeBook {
            get {
                return ResourceManager.GetString("TypeBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Газета#.
        /// </summary>
        public static string TypeNews {
            get {
                return ResourceManager.GetString("TypeNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Патент#.
        /// </summary>
        public static string TypePatent {
            get {
                return ResourceManager.GetString("TypePatent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Год издания:.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы указали Год издания меньше, чем 1900. Вместо него указано значение по умолчанию: {0}..
        /// </summary>
        public static string YearError {
            get {
                return ResourceManager.GetString("YearError", resourceCulture);
            }
        }
    }
}
